### PR TITLE
K8s 8292 create terraform resource for maintenancecronjobs

### PR DESCRIPTION
**Pull request by mmertdogann**

### CODE REVIEW

**Comment by phiphi282** [comment]
Create and read work completely now.
Delete currently throws an error because of mismatching error codes from the api.
Update is currently broken on api side.

Both issues don't need to be fixed here but in the api.

**Comment by phiphi282** [comment]
> @phiphi282 , would it make sense to add a usage example to the existing examples?

I'd create the example in a second pr later on. This way the pull requests are a bit smaller and easier to review.

**Comment by nrobert13** [comment]
> > @phiphi282 , would it make sense to add a usage example to the existing examples?
> 
> I'd create the example in a second pr later on. This way the pull requests are a bit smaller and easier to review.

I'd rather keep it in one PR, it's maybe 15 lines of code in one file...

**Comment by nrobert13** [comment]
@phiphi282 lgtm, you may go ahead and merge it.

**Pull request merged**
